### PR TITLE
Fixes handling of complex data structures in parameters (Closes #189)

### LINKED ISSUE #189: Parameter priority - complex data structures
Checking for existence is not enough for parameters with things like objects and arrays. See original comment made on this [here](https://github.com/rooseveltframework/roosevelt/issues/168#issuecomment-312087813)

To re-iterate:

Pick a roosevelt param that is an object we will use `validatorExceptions`. This object accepts two possible keys `requestHeader` and `modelValue`.

If I was to specify the `validatorExceptions` object in the `package.json` with only one key like:

```json
{"requestHeader": "Partial"}
```

Source params does this check:

```javascript
params.validatorExceptions !== undefined ? params.validatorExceptions : pkg.rooseveltConfig.validatorExceptions !== undefined ? pkg.rooseveltConfig.validatorExceptions : defaultConfig.validatorExceptions
```

So `validatorExceptions` is defined in the `package.json` but not **all** keys are defined. But we can never move onto the defaults because it is present in the `package.json` so `modelValue` gets set to null. This can cause problems. Objects and arrays will need more stringent checks.

### PR DESCRIPTION
**Pull request by dishad**
Created a function that handles objects and other regular parameters. 

Closes #189

### CODE REVIEW

**Comment by Autre31415** [comment]
@kethinov What do you think of renaming `lib/checkFiles.js` to something more generic like `common.js` and moving the `checkObject` and `checkParams` functions into it?

**Comment by kethinov** [comment]
i'd go with `utils.js` but otherwise sounds good

**Comment by Autre31415** [comment]
In that case @dishad when you do that be sure to replace any instance of `checkFiles` with `utils` wherever it's required across the codebase.

**Comment by dishad** [comment]
Sounds good ill update this PR

**Comment by Autre31415** [comment]
LGTM

**Pull request merged**
