### PR TITLE
Fixed bug to make Roosevelt respond to NODE_ENV properly (Closes #970)

### LINKED ISSUE #970: Roosevelt doesn't listen to NODE_ENV as stated in the README
The Roosevelt [README](https://github.com/rooseveltframework/roosevelt/tree/5ad71bd9e578dc5898dc6508b05d7f1327bc353b#recognized-environment-variables) states that the app listens to `NODE_ENV` to set the app to `production` or `development`

I did a global search in the code base and it only listens to params to set the app mode, these ENVs are not honored. https://github.com/rooseveltframework/roosevelt/blob/master/lib/sourceParams.js#L407-L417

I noticed this a long time ago but never looked into it until now so I can't tell you the last time it was working properly (if at all).

### PR DESCRIPTION
**Pull request by alallier**
When a command line argument for node environment isn't specified, look next to NODE_ENV, then fallback to production default

(Closes #970)

### CODE REVIEW

**Comment by kethinov** [comment]
LGTM.

@Autre31415 can you review and merge if this looks good to you?

**Review by kethinov — DISMISSED** [review]

**Comment by alallier** [comment]
I worried these lines below would clobber the terminal set ENV but it doesn't seem to so 🤷‍♂️ 

https://github.com/rooseveltframework/roosevelt/blob/master/lib/sourceParams.js#L408

**Review by lannonbr — APPROVED** [review]
LGTM

**Comment by alallier** [comment]
Hunch here. The unit tests are probably hosed because CI environments typically have NODE_ENV set to production and now Roosevelt respects it. Not sure if the tests are settings the command line args

**Comment by kethinov** [comment]
Do the tests work locally?

**Comment by alallier** [comment]
Nah they are hosed too it seems

**Review by kethinov — APPROVED** [review]

**Comment by kethinov** [comment]
@Autre31415 please merge if you concur.

**Pull request merged**
