### PR TITLE
HTTPS CA / Accept fully-realized string input

### PR DESCRIPTION
**Pull request by jkae**
#245 - Implementation of discussed option 2

- try/catch around reading CA files
- assume string keys if File Not Found
  - if any fail, apply assumption to entire array
- allow https server to deal with bad CA input

This is just a quick and dirty solution, but I'm willing to go with whatever implementation might be desired.

### CODE REVIEW

**Comment by kethinov** [comment]
You should close this and reopen it with a commit bound to the email address that is actually associated with your GitHub account.

**Comment by jkae** [comment]
I thought it was but it turns out I was wrong.

**Comment by kethinov** [comment]
Sorry when I said reopen, I meant a fresh PR without the tainted history.

**Comment by alallier** [comment]
You could always re-write the authorship and force push the branch

**Pull request closed without merging**
