### PR TITLE
Removed res.statusCode === 200 from injectReload.js

### LINKED ISSUE #738: Run frontend reload on HTML validator error page

### PR DESCRIPTION
**Pull request by fboechats**
Closes #738

### CODE REVIEW

**Comment by marclerodrigues** [comment]
Could you add a little bit of context why you made this change?

**Comment by alallier** [comment]
Let me link in the issue. That should help with the context

**Comment by fboechats** [comment]
My bad, forgot to mention the issue.

**Comment by alallier** [comment]
Not a problem @fboechats!

**Comment by kethinov** [comment]
Thanks!

**Pull request merged**
